In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
p = Path('../../../data/raw/lecture/public-covid-data/')

In [33]:
target_folder = ['rp_im', 'rp_msk']
df_list = []

for folder in p.iterdir():
    if os.path.split(folder)[-1] in target_folder:
        df_list.append(pd.DataFrame({
            'path': [sub_p.as_posix() for sub_p in folder.iterdir()],
            'filename': [os.path.split(sub_p)[-1] for sub_p in folder.iterdir()],
        }))
df = df_list[0].merge(df_list[1], on='filename', suffixes=('_im', '_msk'))
df

,path_im,filename,path_msk
0,../../../data/raw/lecture/public-covid-data/rp...,5.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
1,../../../data/raw/lecture/public-covid-data/rp...,9.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
2,../../../data/raw/lecture/public-covid-data/rp...,7.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
3,../../../data/raw/lecture/public-covid-data/rp...,3.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
4,../../../data/raw/lecture/public-covid-data/rp...,1.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
5,../../../data/raw/lecture/public-covid-data/rp...,4.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
6,../../../data/raw/lecture/public-covid-data/rp...,8.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
7,../../../data/raw/lecture/public-covid-data/rp...,6.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
8,../../../data/raw/lecture/public-covid-data/rp...,2.nii.gz,../../../data/raw/lecture/public-covid-data/rp...

In [44]:
p = Path('../../../data/raw/lecture/public-covid-data/')

In [56]:
target_folders = {'rp_im', 'rp_msk'}
dfs = {}

for folder in p.iterdir():
    if not folder.name in target_folders:
        continue

    files = list(folder.iterdir())
    dfs[folder.name] = pd.DataFrame({
        'filename': [f.name for f in files],
        'path': [f.as_posix() for f in files],
    })

df = dfs['rp_im'].merge(
    dfs['rp_msk'],
    on='filename',
    suffixes=('_im', '_msk'),
)

df

,filename,path_im,path_msk
0,5.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
1,9.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
2,7.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
3,3.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
4,1.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
5,4.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
6,8.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
7,6.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...
8,2.nii.gz,../../../data/raw/lecture/public-covid-data/rp...,../../../data/raw/lecture/public-covid-data/rp...

In [54]:
dfs.keys()

dict_keys(['rp_im', 'rp_msk'])

In [55]:
dfs.items()

dict_items([('rp_im',    filename                                               path
0  5.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
1  9.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
2  7.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
3  3.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
4  1.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
5  4.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
6  8.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
7  6.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
8  2.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...), ('rp_msk',    filename                                               path
0  5.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
1  9.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
2  7.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
3  3.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
4  1.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
5  4.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
6  8.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
7  6.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...
8  2.nii.gz  ../../../data/raw/lecture/public-covid-data/rp...)])