In [1]:
from tqdm import tqdm

In [3]:
tqdm()

0it [00:00, ?it/s]

In [6]:
import time

n = 0
before = time.time()
for i in tqdm(range(int(1e7)), position=0):
   n += 1
print(n)
after = time.time()
print(f'Time: {after - before}sec')

100%|██████████| 10000000/10000000 [00:01<00:00, 9365818.80it/s]

10000000
Time: 1.0708563327789307sec

In [7]:
import pandas as pd

In [14]:
data = {
    'Name': ['luffy', 'nami', 'zoro'],
    'Age': [19, 20, 21]
}

In [15]:
data

{'Name': ['luffy', 'nami', 'zoro'], 'Age': [19, 20, 21]}

In [16]:
pd.DataFrame(data)

    Name  Age
0  luffy   19
1   nami   20
2   zoro   21

In [21]:
import os
from pathlib import Path

In [19]:
im_path_list = []
msk_path_list = []
filename_list = []

p = Path('../../../data/raw/lecture/public-covid-data/')

data = {
    'path_im': im_path_list,
    'filename': filename_list,
    'path_msk': msk_path_list,
}

In [20]:
pd.DataFrame(data)

Empty DataFrame
Columns: [path_im, filename, path_msk]
Index: []

In [37]:
p = Path('../../../data/raw/lecture/public-covid-data/')
p

PosixPath('../../../data/raw/lecture/public-covid-data')

In [38]:
for sub_p in list(p.iterdir()):
    if str(sub_p).split('/')[-1] == 'rp_im':
        im_p = sub_p.iterdir()
        for p in im_p:
            im_path_list.append(p)
            path, file = os.path.split(p)
            filename_list.append(file)
    elif str(sub_p).split('/')[-1] == 'rp_msk':
        msk_p = sub_p.iterdir()
        for p in msk_p:
            msk_path_list.append(p)

In [41]:
data = {
    'path_im': im_path_list,
    'filename': filename_list,
    'path_msk': msk_path_list,
}

In [45]:
df = pd.DataFrame(data)
df

,path_im,filename,path_msk
0,../../../data/raw/lecture/public-covid-data/rp...,5.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
1,../../../data/raw/lecture/public-covid-data/rp...,9.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
2,../../../data/raw/lecture/public-covid-data/rp...,7.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
3,../../../data/raw/lecture/public-covid-data/rp...,3.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
4,../../../data/raw/lecture/public-covid-data/rp...,1.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
5,../../../data/raw/lecture/public-covid-data/rp...,4.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
6,../../../data/raw/lecture/public-covid-data/rp...,8.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
7,../../../data/raw/lecture/public-covid-data/rp...,6.nii.gz,../../../data/raw/lecture/public-covid-data/rp...
8,../../../data/raw/lecture/public-covid-data/rp...,2.nii.gz,../../../data/raw/lecture/public-covid-data/rp...

In [49]:
type(df['path_im'][0])

pathlib.PosixPath

In [57]:
p = Path('../../../data/raw/lecture/public-covid-data/')

In [56]:
for folder in p.iterdir():
    if not (os.path.split(folder)[1] == 'rp_im') or ((os.path.split(folder)[1] == 'rp_msk')):
        pass
    print(folder)

../../../data/raw/lecture/public-covid-data/new_folder
../../../data/raw/lecture/public-covid-data/rp_im
../../../data/raw/lecture/public-covid-data/rp_msk

In [61]:
folder = list(p.iterdir())
folder

[PosixPath('../../../data/raw/lecture/public-covid-data/new_folder'),
 PosixPath('../../../data/raw/lecture/public-covid-data/rp_im'),
 PosixPath('../../../data/raw/lecture/public-covid-data/rp_msk')]

In [64]:
[os.path.split(p)[-1] for p in list(folder[1].iterdir())]

['5.nii.gz',
 '9.nii.gz',
 '7.nii.gz',
 '3.nii.gz',
 '1.nii.gz',
 '4.nii.gz',
 '8.nii.gz',
 '6.nii.gz',
 '2.nii.gz']

0
1
2

IndexError: list index out of range

IndexError: list index out of range