In [3]:
import pandas as pd
import numpy as np

In [8]:
ndarray = np.arange(10).reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
pd.DataFrame(ndarray, index=['index1', 'index2'], columns=['a', 'b', 'c', 'd', 'e'])

        a  b  c  d  e
index1  0  1  2  3  4
index2  5  6  7  8  9

In [12]:
data_1 = {
    'Name': 'aki',
    'Sex': 'male',
    'Age': 35,
}
data_2 = {
    'Name': 'Luffy',
    'Sex': 'male',
    'Age': 19,
}
data_3 = {
    'Name': 'Nami',
    'Sex': 'female',
    'Age': 21,
}
pd.DataFrame([data_1, data_2, data_3])

    Name     Sex  Age
0    aki    male   35
1  Luffy    male   19
2   Nami  female   21

In [14]:
data = {
    'Name': ['Luffy', 'Zoro', 'Nami'],
    'Sex': ['male', 'male', 'female'],
    'Age': [19, 21, 20]
}
df = pd.DataFrame(data)
df

    Name     Sex  Age
0  Luffy    male   19
1   Zoro    male   21
2   Nami  female   20