In [2]:
import numpy as np
import pandas as pd

In [1]:
data1 = {
    'key': ['k0', 'k1', 'k2'],
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2'],
}
data2 = {
    'key': ['k0', 'k1', 'k2'],
    'C': ['c0', 'c1', 'c2'],
    'D': ['d0', 'd1', 'd2'],
}

In [3]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [4]:
df1

  key   A   B
0  k0  a0  b0
1  k1  a1  b1
2  k2  a2  b2

In [5]:
df2

  key   C   D
0  k0  c0  d0
1  k1  c1  d1
2  k2  c2  d2

In [6]:
pd.concat([df1, df2])

  key    A    B    C    D
0  k0   a0   b0  NaN  NaN
1  k1   a1   b1  NaN  NaN
2  k2   a2   b2  NaN  NaN
0  k0  NaN  NaN   c0   d0
1  k1  NaN  NaN   c1   d1
2  k2  NaN  NaN   c2   d2

In [7]:
pd.concat([df1, df2], axis=1)

  key   A   B key   C   D
0  k0  a0  b0  k0  c0  d0
1  k1  a1  b1  k1  c1  d1
2  k2  a2  b2  k2  c2  d2

In [8]:
df1.merge(df2)

  key   A   B   C   D
0  k0  a0  b0  c0  d0
1  k1  a1  b1  c1  d1
2  k2  a2  b2  c2  d2

In [9]:
data1 = {
    'key': ['k0', 'k1', 'k2'],
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2'],
}
data2 = {
    'key': ['k0', 'k1', 'k3'],
    'C': ['c0', 'c1', 'c3'],
    'D': ['d0', 'd1', 'd3'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [10]:
df1

  key   A   B
0  k0  a0  b0
1  k1  a1  b1
2  k2  a2  b2

In [11]:
df2

  key   C   D
0  k0  c0  d0
1  k1  c1  d1
2  k3  c3  d3

In [19]:
df1.merge(df2, how='left', on='key')

  key   A   B    C    D
0  k0  a0  b0   c0   d0
1  k1  a1  b1   c1   d1
2  k2  a2  b2  NaN  NaN

In [23]:
data1 = {
    'Key': ['k0', 'k1', 'k2'],
    'ID': ['aa', 'bb', 'cc'],
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2'],
}
data2 = {
    'Key': ['k0', 'k1', 'k3'],
    'ID': ['aa', 'bb', 'cc'],
    'C': ['c0', 'c1', 'c3'],
    'D': ['d0', 'd1', 'd3'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [25]:
df1.merge(df2, on='Key', suffixes=('_right', '_Left'))

  Key ID_right   A   B ID_Left   C   D
0  k0       aa  a0  b0      aa  c0  d0
1  k1       bb  a1  b1      bb  c1  d1

In [26]:
data1 = {
    'Key1': ['k0', 'k1', 'k2'],
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2'],
}
data2 = {
    'Key2': ['k0', 'k1', 'k3'],
    'C': ['c0', 'c1', 'c3'],
    'D': ['d0', 'd1', 'd3'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [29]:
df1.merge(df2, left_on='Key1', right_on='Key2')

  Key1   A   B Key2   C   D
0   k0  a0  b0   k0  c0  d0
1   k1  a1  b1   k1  c1  d1

In [30]:
df1.merge(df2, left_index=True, right_index=True)

  Key1   A   B Key2   C   D
0   k0  a0  b0   k0  c0  d0
1   k1  a1  b1   k1  c1  d1
2   k2  a2  b2   k3  c3  d3

In [39]:
df_movies = pd.read_csv('../../../data/raw/lecture/tmdb_5000_movies.csv')
df_credits = pd.read_csv('../../../data/raw/lecture/tmdb_5000_credits.csv')

In [32]:
print(len(df_movies))
print(len(df_credits))

4803
4803

In [33]:
print(df_movies.columns)
print(df_credits.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [41]:
df = df_movies.merge(df_credits, 
                     left_on='id', right_on='movie_id', 
                     suffixes=('_movies', '_credits'))
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [42]:
len(df)

4803

In [45]:
data1 = {
    'Key1': ['k0', 'k1', 'k2'],
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2'],
}
data2 = {
    'Key2': ['k0', 'k1', 'k3'],
    'C': ['c0', 'c1', 'c3'],
    'D': ['d0', 'd1', 'd3'],
}
data3 = {
    'Key3': ['k0', 'k1', 'k3'],
    'E': ['e0', 'e1', 'e3'],
    'F': ['f0', 'f1', 'f3'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

In [46]:
df1.join([df2, df3])

  Key1   A   B Key2   C   D Key3   E   F
0   k0  a0  b0   k0  c0  d0   k0  e0  f0
1   k1  a1  b1   k1  c1  d1   k1  e1  f1
2   k2  a2  b2   k3  c3  d3   k3  e3  f3